/**
 * Host nation for UNL home fixtures — league-phase matches are hosted by the home side.
 */

const HOST_COUNTRY_BY_FLAG: Record<string, string> = {
  fr: "France",
  it: "Italy",
  be: "Belgium",
  tr: "Türkiye",
  de: "Germany",
  nl: "Netherlands",
  rs: "Serbia",
  gr: "Greece",
  es: "Spain",
  hr: "Croatia",
  "gb-eng": "England",
  cz: "Czechia",
  pt: "Portugal",
  dk: "Denmark",
  no: "Norway",
  "gb-wls": "Wales",
  "gb-sct": "Scotland",
  ch: "Switzerland",
  si: "Slovenia",
  mk: "North Macedonia",
  hu: "Hungary",
  ua: "Ukraine",
  ge: "Georgia",
  "gb-nir": "Northern Ireland",
  il: "Israel",
  at: "Austria",
  ie: "Republic of Ireland",
  xk: "Kosovo",
  pl: "Poland",
  ba: "Bosnia and Herzegovina",
  ro: "Romania",
  se: "Sweden",
  al: "Albania",
  fi: "Finland",
  by: "Belarus",
  sm: "San Marino",
  me: "Montenegro",
  am: "Armenia",
  cy: "Cyprus",
  lv: "Latvia",
  kz: "Kazakhstan",
  sk: "Slovakia",
  fo: "Faroe Islands",
  md: "Moldova",
  is: "Iceland",
  bg: "Bulgaria",
  ee: "Estonia",
  lu: "Luxembourg",
  gi: "Gibraltar",
  ad: "Andorra",
  mt: "Malta",
  lt: "Lithuania",
  az: "Azerbaijan",
  li: "Liechtenstein",
};

const HOST_COUNTRY_BY_NAME: Record<string, string> = {
  France: "France",
  Italy: "Italy",
  Belgium: "Belgium",
  Türkiye: "Türkiye",
  Germany: "Germany",
  Netherlands: "Netherlands",
  Serbia: "Serbia",
  Greece: "Greece",
  Spain: "Spain",
  Croatia: "Croatia",
  England: "England",
  Czechia: "Czechia",
  Portugal: "Portugal",
  Denmark: "Denmark",
  Norway: "Norway",
  Wales: "Wales",
  Scotland: "Scotland",
  Switzerland: "Switzerland",
  Slovenia: "Slovenia",
  "North Macedonia": "North Macedonia",
  Hungary: "Hungary",
  Ukraine: "Ukraine",
  Georgia: "Georgia",
  "Northern Ireland": "Northern Ireland",
  Israel: "Israel",
  Austria: "Austria",
  "Republic of Ireland": "Republic of Ireland",
  Kosovo: "Kosovo",
  Poland: "Poland",
  "Bosnia and Herzegovina": "Bosnia and Herzegovina",
  Romania: "Romania",
  Sweden: "Sweden",
  Albania: "Albania",
  Finland: "Finland",
  Belarus: "Belarus",
  "San Marino": "San Marino",
  Montenegro: "Montenegro",
  Armenia: "Armenia",
  Cyprus: "Cyprus",
  Latvia: "Latvia",
  Kazakhstan: "Kazakhstan",
  Slovakia: "Slovakia",
  "Faroe Islands": "Faroe Islands",
  Moldova: "Moldova",
  Iceland: "Iceland",
  Bulgaria: "Bulgaria",
  Estonia: "Estonia",
  Luxembourg: "Luxembourg",
  Gibraltar: "Gibraltar",
  Andorra: "Andorra",
  Malta: "Malta",
  Lithuania: "Lithuania",
  Azerbaijan: "Azerbaijan",
  Liechtenstein: "Liechtenstein",
};

/** Country where a home UNL fixture is hosted. */
export function getUnlHostCountry(
  homeTeamName: string,
  homeTeamFlag?: string | null,
): string {
  const byFlag = homeTeamFlag
    ? HOST_COUNTRY_BY_FLAG[homeTeamFlag.trim().toLowerCase()]
    : undefined;
  if (byFlag) return byFlag;
  return HOST_COUNTRY_BY_NAME[homeTeamName] ?? homeTeamName;
}

export function formatUnlHostLabel(
  homeTeamName: string,
  homeTeamFlag?: string | null,
): string {
  return `Played in ${getUnlHostCountry(homeTeamName, homeTeamFlag)}`;
}